### PR TITLE
Feature: Ubuntu 16.04 support

### PR DESCRIPTION
**Pull request by lsh-0**
removed connection parameters from mysql states

### CODE REVIEW

**Comment by nlisgo** [comment]
@lsh-0 were you waiting on feedback as to whether to proceed with this and other similar PR's? Apologies for not spotting this sooner.

**Comment by lsh-0** [comment]
hey @nlisgo , good to hear from you.

no, I don't think you were blocking anything here. All formulas have a 16.04 branch but I was going to merge them as the machines themselves were replaced. 

Replacing single node machines means downtime/unavailable services so we've been holding off on the migration.

I do worry about them getting stale, though. I finished a bit of work on builder yesterday that lets us test formula changes by building them from scratch. What we're currently doing is building the master from scratch, switching the branch on the formula and then calling highstate again. This is how updates are applied to running machines normally. Building both ways, from scratch and as an upgrade, will be really beneficial for these 16.04 branches.

Once the builder change is merged and @giorgiosironi has time to run the new types of tests, I'll revisit each of these 16.04 formulas and get them merged in.

**Comment by giorgiosironi** [comment]
> Building both ways, from scratch and as an upgrade, will be really beneficial for these 16.04 branches.

For their backward compatibility, yes; but they will still only be built with 14.04 so we may look into how to build *also* from a 16.04 AMI (3rd build?)

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/medium-formula/pull/5 is the first one where I am experimenting with a `fresh` phase of the build.

**Comment by giorgiosironi** [comment]
(There is no parallelism so far)

**Comment by lsh-0** [comment]
you're right, but it should just be a matter of specifying an alternate config on a fresh build, right? `./bldr masterless.launch:lax,instanceid,standalone1604,builder-base-formula@1604-branch,lax-formula@1604-branch`

**Comment by lsh-0** [comment]
dropping this back down to 16.04 support given lack of comms with Nathan and the php7 ppa going away on 14.04

**Comment by lsh-0** [comment]
journal-cms is building perfectly on a 16.04 vagrant vm

**Comment by lsh-0** [comment]
the failures here are because the php ppa for 14.04 has gone away.

I'm going to bring up an adhoc instance and attempt a restore from backup.

**Pull request merged**
